spring:
  application:
    name: security

  datasource:
    url: jdbc:h2:mem:security
    driver-class-name: org.h2.Driver
  redis:
    host: localhost
    port: 6379

  jpa:
    hibernate:
      ddl-auto: update
      show-sql: true
      database-platform: org.hibernate.dialect.H2Dialect

  security:
    secret-key: ${JWT_SECRET}
    aes-key: ${AES_KEY}
    token-expiration-time: 36_000_000  #
    reset-pass-token-expiration-time: 300_000 # 5m
    verification-token-expiration-time: 300_000 # 5m
    invalid-login-attempts: 3
    wait-time-m: 2

  mail:
    host: smtp.gmail.com
    port: 587
    username: ${EMAIL}
    password: ${EMAIL_PASS}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
