spring:
  application:
    name: security

  datasource:
    url: jdbc:h2:mem:security
    driver-class-name: org.h2.Driver
  redis:
    host: localhost
    port: 6379

  jpa:
    hibernate:
      ddl-auto: update
      show-sql: true
      database-platform: org.hibernate.dialect.H2Dialect

  security:
    secret-key: ${JWT_SECRET}
    token-expiration-time: 36_000_000


  mail:
    host: smtp.gmail.com
    port: 587
    username: ${EMAIL}
    password: ${EMAIL_PASS}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
